POST http://localhost:8080/execute
Content-Type: application/json

{
  "script": "POSITION 1 3 EAST //sets the initial position for the robot as x, y. \n FORWARD 3 //lets the robot do 3 steps forward WAIT //lets the robot do nothing\nTURNAROUND //lets the robot turn around \nFORWARD 1 //lets the robot do 1 step forward\n RIGHT //lets the robot turn right\nFORWARD 2 //lets the robot do 2 steps forward",
  "position": {
    "x":"0",
    "y": "0",
    "direction": "EAST"
  }
}
